In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import json

import warnings
warnings.filterwarnings("ignore")

print('numpy version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

def seriesinfo(s) :
    print('index - ' , s.index , type(s.index))
    print('value - ' , s.values , type(s.values))
    print()
    print('data - ')
    print(s)
    
def frminfo(df) :
    print('shape     - ' , df.shape)
    print('size      - ' , df.size)
    print('ndim      - ' , df.ndim )
    print('index     - ' , df.index   , type(df.index))
    print('col index - ' , df.columns , type(df.columns))
    print('values    - ')
    print(df.values  , '\n' , type(df.values))
    print()
    print('data - ')
    display(df)

numpy version -  1.21.5
pandas version -  1.4.4

In [ ]:
[실습01]
지역으로 시작하는 모든 파일을 로드하고 병합


[실습02]
기본정보 확인 및 결측치 확인

[실습03]
휘발유를 대상으로 분석 진행하기위해서 컬럼명 변경하여 서브셋 만들기

#          상호,       주소,     휘발유, 셀프여부 , 상표
# rename   oil_store , address , price , self_y_n , company

[실습04]
구별 주유소 가격을 조사하기 위해서 파생변수 생성(direct)
구별 정보확인
서울특별시 -> 성동구 대체
특별시 -> 도봉구 대체


[실습05]
가격 정보 확인[ - 들어있음] 후
가격 정보가 기입되지 않은 주유소는 제거
컬럼 타입을 숫자형으로 변경

[실습06]
인덱스를 새롭게 정의(reset_index)
인덱스열을 제거


[실습07]
박스플롯을 이용한 셀프여부 비교 시각화(휘발유 가격차이 확인)
회사 및 구별 휘발유 가격 평균가격 확인


[실습08]
구별 휘발유 평균가격 확인


[실습09]
구분구획선(Choropleth) 이용한 시각화

[실습10]
제공된 json 파일을 이용하여 구분구획선 지도 시각화 준비
서울지역 주유가격 상위 10, 하위 10 확인
googlemap을 이용한 위도경도 추출
데이터에 위도, 경도 추가하여
주유가격 상위 10, 하위 10 개 folium marker를 이용한 시각화

- 주유소 평균가격 확인
- 셀프 주유소는 정말 저렴할까?

In [12]:
# 비슷한 이름의 파일을 다량으로 불러와 리스트에 저장

from glob import glob

print('step01 - ')
print('glob()함수 파일 경로 등을 쉽게 접근할 수 있도록 도와주는 모듈의 함수')
stations_files = glob('C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data/지역*.xls')
stations_files

step01 -
glob()함수 파일 경로 등을 쉽게 접근할 수 있도록 도와주는 모듈의 함수

['C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (1).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (10).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (11).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (12).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (13).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (14).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (15).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (16).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (17).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (18).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (19).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (2).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (20).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (21).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (22).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (23).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (24).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (3).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (4).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (5).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (6).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (7).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (8).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소) (9).xls',
 'C:/Users/PiGiraffe0/Documents/SQL/data/test/oil_data\\지역_위치별(주유소).xls']

In [48]:
lst = []
for i in range(1,25) :
    lst.append(pd.read_excel(stations_files[i] , header = 2))
station_raw = pd.concat(lst)
station_raw.info()
station_raw.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518 entries, 0 to 45
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      518 non-null    object
 1   상호      518 non-null    object
 2   주소      518 non-null    object
 3   상표      518 non-null    object
 4   전화번호    518 non-null    object
 5   셀프여부    518 non-null    object
 6   고급휘발유   518 non-null    object
 7   휘발유     518 non-null    object
 8   경유      518 non-null    object
 9   실내등유    518 non-null    object
dtypes: object(10)
memory usage: 44.5+ KB

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,SK경동주유소,서울 동대문구 이문로 191 (이문동),SK에너지,02-962-5188,N,-,1515,1305,1100
1,서울특별시,삼미상사(주)장안킹셀프주유소,서울특별시 동대문구 한천로 100 (장안동),SK에너지,02-2242-7115,Y,-,1515,1305,-
2,서울특별시,웰컴주유소,서울특별시 동대문구 한천로 414 (이문동),현대오일뱅크,02-969-1144,N,-,1515,1305,-
3,서울특별시,(주)열린주유소,서울 동대문구 한천로 263 (휘경동),GS칼텍스,070-4413-6542,N,-,1515,1305,1100
4,서울특별시,재정제2주유소,서울 동대문구 사가정로 90 (전농동),현대오일뱅크,02-2249-6682,Y,-,1519,1319,-

In [33]:
# 데이터 확인 및 구조 분석과 각 데이터 프레임에 헤더를 추가

In [37]:
print('step02 - 휘발유 대상으로 칼럼 변경하여 서브셋 만들기')

step02 - 휘발유 대상으로 칼럼 변경하여 서브셋 만들기

In [96]:
station_raw.rename(columns = {'상호' : 'oli_store' , '주소' : 'address' , '휘발유' : 'price' , '상표' : 'company' , '셀프여부' : 'self_y_n'} , inplace=True)
gasoline_frm = station_raw
gasoline_frm = gasoline_frm.drop(['지역' , '전화번호' , '고급휘발유' , '경유' , '실내등유'] , axis = 1).reset_index(drop=True)
gasoline_frm

           oli_store                    address company self_y_n price
0            SK경동주유소      서울 동대문구 이문로 191 (이문동)   SK에너지        N  1515
1    삼미상사(주)장안킹셀프주유소  서울특별시 동대문구  한천로 100 (장안동)   SK에너지        Y  1515
2              웰컴주유소  서울특별시 동대문구  한천로 414 (이문동)  현대오일뱅크        N  1515
3           (주)열린주유소      서울 동대문구 한천로 263 (휘경동)   GS칼텍스        N  1515
4            재정제2주유소      서울 동대문구 사가정로 90 (전농동)  현대오일뱅크        Y  1519
..               ...                        ...     ...      ...   ...
513          갤러리아주유소      서울 강남구 압구정로 426 (청담동)   SK에너지        N  2059
514            동우주유소  서울특별시 강남구  봉은사로 311 (논현동)   SK에너지        N  2105
515            삼성주유소       서울 강남구 삼성로 521 (삼성동)   SK에너지        N  2106
516            오천주유소      서울 강남구 봉은사로 503 (삼성동)   SK에너지        N  2107
517          뉴서울(강남)       서울 강남구 언주로 716 (논현동)   SK에너지        N  2120

[518 rows x 5 columns]

In [47]:
# 구별 주유소 가격을 조사하기 위해서 파생변수 생성(direct)
# 구별 정보 확인
# gasoline_frm['address'][i].split(' ')[0] == '서울특별시' or gasoline_frm['address'][i].split(' ')[1] == '서울특별시':

In [77]:
gasoline_frm.reset_index(drop=True , inplace=True)
lst = []
for i in range(len(gasoline_frm)) :
    # print(gasoline_frm['address'][i].split(' '))    
    if '서울특별시' in gasoline_frm['address'][i].split(' '):
        lst.append('성동구')
    else :
        lst.append(gasoline_frm['address'][i].split(' ')[1])

gasoline_frm['direct'] = lst
gasoline_frm

           oli_store                    address company self_y_n price direct
0            SK경동주유소      서울 동대문구 이문로 191 (이문동)   SK에너지        N  1515   동대문구
1    삼미상사(주)장안킹셀프주유소  서울특별시 동대문구  한천로 100 (장안동)   SK에너지        Y  1515    성동구
2              웰컴주유소  서울특별시 동대문구  한천로 414 (이문동)  현대오일뱅크        N  1515    성동구
3           (주)열린주유소      서울 동대문구 한천로 263 (휘경동)   GS칼텍스        N  1515   동대문구
4            재정제2주유소      서울 동대문구 사가정로 90 (전농동)  현대오일뱅크        Y  1519   동대문구
..               ...                        ...     ...      ...   ...    ...
513          갤러리아주유소      서울 강남구 압구정로 426 (청담동)   SK에너지        N  2059    강남구
514            동우주유소  서울특별시 강남구  봉은사로 311 (논현동)   SK에너지        N  2105    성동구
515            삼성주유소       서울 강남구 삼성로 521 (삼성동)   SK에너지        N  2106    강남구
516            오천주유소      서울 강남구 봉은사로 503 (삼성동)   SK에너지        N  2107    강남구
517          뉴서울(강남)       서울 강남구 언주로 716 (논현동)   SK에너지        N  2120    강남구

[518 rows x 6 columns]

In [97]:
gasoline_frm.reset_index(drop=True , inplace=True)
lst = []
for i in gasoline_frm['address'] :
    # print(gasoline_frm['address'][i].split(' '))    
    if '서울특별시' in i.split(' '):
        lst.append('성동구')
    else :
        lst.append(i.split(' ')[1])

gasoline_frm['direct'] = lst
gasoline_frm

           oli_store                    address company self_y_n price direct
0            SK경동주유소      서울 동대문구 이문로 191 (이문동)   SK에너지        N  1515   동대문구
1    삼미상사(주)장안킹셀프주유소  서울특별시 동대문구  한천로 100 (장안동)   SK에너지        Y  1515    성동구
2              웰컴주유소  서울특별시 동대문구  한천로 414 (이문동)  현대오일뱅크        N  1515    성동구
3           (주)열린주유소      서울 동대문구 한천로 263 (휘경동)   GS칼텍스        N  1515   동대문구
4            재정제2주유소      서울 동대문구 사가정로 90 (전농동)  현대오일뱅크        Y  1519   동대문구
..               ...                        ...     ...      ...   ...    ...
513          갤러리아주유소      서울 강남구 압구정로 426 (청담동)   SK에너지        N  2059    강남구
514            동우주유소  서울특별시 강남구  봉은사로 311 (논현동)   SK에너지        N  2105    성동구
515            삼성주유소       서울 강남구 삼성로 521 (삼성동)   SK에너지        N  2106    강남구
516            오천주유소      서울 강남구 봉은사로 503 (삼성동)   SK에너지        N  2107    강남구
517          뉴서울(강남)       서울 강남구 언주로 716 (논현동)   SK에너지        N  2120    강남구

[518 rows x 6 columns]

In [98]:
gasoline_frm['direct'].unique()

array(['동대문구', '성동구', '동작구', '마포구', '서대문구', '서초구', '성북구', '송파구', '양천구',
       '영등포구', '강북구', '용산구', '은평구', '종로구', '중구', '중랑구', '강서구', '관악구',
       '광진구', '구로구', '금천구', '노원구', '도봉구', '특별시', '강남구'], dtype=object)

In [100]:
gasoline_frm['direct'][gasoline_frm['direct']=='특별시'] = '도봉구'
gasoline_frm.loc[462]

oli_store                       서현주유소
address      서울 특별시 도봉구 방학로 142 (방학동)
company                         S-OIL
self_y_n                            Y
price                            1524
direct                            도봉구
Name: 462, dtype: object

In [103]:
gasoline_frm['direct'].unique()

array(['동대문구', '성동구', '동작구', '마포구', '서대문구', '서초구', '성북구', '송파구', '양천구',
       '영등포구', '강북구', '용산구', '은평구', '종로구', '중구', '중랑구', '강서구', '관악구',
       '광진구', '구로구', '금천구', '노원구', '도봉구', '강남구'], dtype=object)

In [119]:
# gasoline_frm['price'].isnull()
# 주유소 price 값이 없는 주유소 삭제
pd.set_option('display.max_rows', None)
gasoline_frm.drop(list(gasoline_frm[gasoline_frm['price']=='-'].index) , axis = 0 , inplace=True)

In [131]:
gasoline_frm.reset_index(drop=True , inplace=True)
gasoline_frm['price'] = gasoline_frm['price'].astype(int)
gasoline_frm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   oli_store  515 non-null    object
 1   address    515 non-null    object
 2   company    515 non-null    object
 3   self_y_n   515 non-null    object
 4   price      515 non-null    int32
 5   direct     515 non-null    object
dtypes: int32(1), object(5)
memory usage: 22.3+ KB

In [133]:
gasoline_frm['price'].unique()

array([1515, 1519, 1522, 1525, 1529, 1539, 1549, 1558, 1568, 1569, 1578,
       1595, 1632, 1692, 1745, 1865, 1499, 1528, 1557, 1598, 1592, 1594,
       1596, 1698, 1748, 1749, 1768, 1775, 1818, 1527, 1535, 1536, 1548,
       1550, 1565, 1790, 1998, 1490, 1537, 1544, 1545, 1554, 1564, 1566,
       1567, 1588, 1597, 1634, 1638, 1648, 1663, 1664, 1899, 1968, 1988,
       2017, 2098, 2128, 1526, 1533, 1579, 1650, 1654, 1848, 1856, 1509,
       1517, 1538, 1547, 1559, 1699, 2065, 1543, 1553, 1555, 1556, 1574,
       1583, 1618, 1627, 1628, 1635, 1658, 1678, 1718, 1737, 1505, 1506,
       1507, 1516, 1546, 1619, 1787, 1829, 1867, 1987, 1518, 1620, 1651,
       1695, 1696, 1793, 1799, 1823, 1835, 1838, 1866, 1870, 1885, 1498,
       1524, 1615, 1608, 1859, 1868, 1997, 2105, 2106, 1534, 1577, 1798,
       1669, 1890, 1960, 2096, 1738, 1898, 1999, 2087, 2099, 2130, 2132,
       1520, 1497, 1513, 1563, 1668, 1877, 1573, 1629, 1675, 1697, 2026,
       1673, 1849, 1532, 1540, 1610, 1688, 1502, 1504, 1508, 1510, 1512,
       1639, 1586, 1590, 1609, 1633, 1685, 1728, 1757, 1780, 1785, 1863,
       1883, 1897, 1937, 1953, 1976, 2006, 2028, 2055, 2059, 2107, 2120])

In [139]:
pd.set_option('display.max_rows', 10)
gasoline_mean_frm = round(gasoline_frm.groupby('direct').agg(np.mean) ,1)
gasoline_mean_frm

         price
direct
강남구     1840.8
강북구     1533.5
강서구     1600.6
관악구     1627.9
광진구     1572.8
...        ...
용산구     1929.9
은평구     1563.8
종로구     2008.4
중구      2012.9
중랑구     1536.9

[24 rows x 1 columns]

In [144]:
# pivot_table로 나타내기

pd.pivot_table(gasoline_frm , index = 'direct' , values = 'price' , aggfunc = np.mean)

              price
direct
강남구     1840.750000
강북구     1533.500000
강서구     1600.588235
관악구     1627.900000
광진구     1572.750000
...             ...
용산구     1929.900000
은평구     1563.833333
종로구     2008.400000
중구      2012.857143
중랑구     1536.857143

[24 rows x 1 columns]

In [145]:
print('step10 - 가격 상위 10개 데이터 , 하위 10개 데이터 추출(dataframe)')

step10 - 가격 상위 10개 데이터 , 하위 10개 데이터 추출(dataframe)

In [148]:
price_top_10_frm = gasoline_frm.sort_values('price' , ascending = False).head(10)
price_bottom_10_frm = gasoline_frm.sort_values('price' , ascending = True).head(10)

display(price_top_10_frm)
display(price_bottom_10_frm)

    oli_store                     address company self_y_n  price direct
307     서남주유소        서울 중구 통일로 30 (봉래동1가)   SK에너지        N   2132     중구
306     장충주유소      서울 중구 장충단로 202 (장충동1가)   SK에너지        N   2130     중구
106     양재주유소       서울 서초구 바우뫼로 178 (양재동)   SK에너지        N   2128    서초구
514   뉴서울(강남)        서울 강남구 언주로 716 (논현동)   SK에너지        N   2120    강남구
513     오천주유소       서울 강남구 봉은사로 503 (삼성동)   SK에너지        N   2107    강남구
265     강변주유소      서울특별시 용산구  원효로 9 (청암동)   SK에너지        N   2106    성동구
266    갈월동주유소   서울특별시 용산구  한강대로 322 (갈월동)   SK에너지        N   2106    성동구
267     청파주유소  서울특별시 용산구  청파로 311 (청파동1가)   SK에너지        N   2106    성동구
305     통일주유소       서울 중구 동호로 296 (장충동2가)   SK에너지        N   2106     중구
295     재동주유소     서울특별시 종로구  율곡로 58 (경운동)   SK에너지        N   2106    성동구

          oli_store                     address company self_y_n  price direct
65         만남의광장주유소  서울 서초구 양재대로12길 73-71 (원지동)  알뜰(ex)        N   1490    서초구
433         태릉솔밭주유소      서울특별시 노원구 노원로 49 (공릉동)   S-OIL        Y   1497    성동구
326       강서오곡셀프주유소     서울특별시 강서구 벌말로 254 (오곡동)   SK에너지        Y   1497    성동구
240          수유동주유소    서울특별시 강북구  도봉로 395 (수유동)   GS칼텍스        Y   1498    성동구
397          풀페이주유소      서울특별시 구로구 경인로 41 (온수동)   SK에너지        N   1499    성동구
207           도림주유소       서울 영등포구 도림로 343 (도림동)   알뜰주유소        Y   1499   영등포구
208  (주)대청에너지 대청주유소      서울 영등포구 가마산로 328 (대림동)   GS칼텍스        N   1499   영등포구
209         (주)강서오일       서울 영등포구 도신로 151 (도림동)  현대오일뱅크        N   1499   영등포구
22            서경주유소        서울 동작구 대림로 46 (신대방동)  현대오일뱅크        N   1499    동작구
308         신일셀프주유소         서울 중랑구 상봉로 58 (망우동)   SK에너지        Y   1499    중랑구

In [151]:
# conda install googlemaps
import googlemaps
gmaps = googlemaps.Client(key = 'AIzaSyBQy1nRN8F9UbiMiWRagzHdhsyy5Dc8dv0')
gmaps

In [153]:
price_top_10_frm['address'].iloc[0]

'서울 중구 통일로 30 (봉래동1가)'

In [177]:
price_top_10_lat = []
price_top_10_lng = []

for address in price_top_10_frm['address'] :
    price_top_10_lat.append(gmaps.geocode(address , language = 'ko')[0].get('geometry')['location']['lat'])
    price_top_10_lng.append(gmaps.geocode(address , language = 'ko')[0].get('geometry')['location']['lng'])


price_top_10_frm['lat'] = price_top_10_lat
price_top_10_frm['lng'] = price_top_10_lng
price_top_10_frm.reset_index(drop=True , inplace=True)
price_top_10_frm

,oli_store,address,company,self_y_n,price,direct,lat,lng
0,서남주유소,서울 중구 통일로 30 (봉래동1가),SK에너지,N,2132,중구,37.559112,126.972491
1,장충주유소,서울 중구 장충단로 202 (장충동1가),SK에너지,N,2130,중구,37.560803,127.007602
2,양재주유소,서울 서초구 바우뫼로 178 (양재동),SK에너지,N,2128,서초구,37.478071,127.039610
3,뉴서울(강남),서울 강남구 언주로 716 (논현동),SK에너지,N,2120,강남구,37.513530,127.031534
4,오천주유소,서울 강남구 봉은사로 503 (삼성동),SK에너지,N,2107,강남구,37.513458,127.053786
5,강변주유소,서울특별시 용산구 원효로 9 (청암동),SK에너지,N,2106,성동구,37.534605,126.948779
6,갈월동주유소,서울특별시 용산구 한강대로 322 (갈월동),SK에너지,N,2106,성동구,37.546955,126.972218
7,청파주유소,서울특별시 용산구 청파로 311 (청파동1가),SK에너지,N,2106,성동구,37.548983,126.967087
8,통일주유소,서울 중구 동호로 296 (장충동2가),SK에너지,N,2106,중구,37.560714,127.003177
9,재동주유소,서울특별시 종로구 율곡로 58 (경운동),SK에너지,N,2106,성동구,37.574357,126.987141

In [179]:
price_bottom_10_lat = []
price_bottom_10_lng = []

for address in price_bottom_10_frm['address'] :
    price_bottom_10_lat.append(gmaps.geocode(address , language = 'ko')[0].get('geometry')['location']['lat'])
    price_bottom_10_lng.append(gmaps.geocode(address , language = 'ko')[0].get('geometry')['location']['lng'])


price_bottom_10_frm['lat'] = price_bottom_10_lat
price_bottom_10_frm['lng'] = price_bottom_10_lng

price_bottom_10_frm.reset_index(drop=True , inplace=True)
price_bottom_10_frm

,oli_store,address,company,self_y_n,price,direct,lat,lng
0,만남의광장주유소,서울 서초구 양재대로12길 73-71 (원지동),알뜰(ex),N,1490,서초구,37.459906,127.042060
1,태릉솔밭주유소,서울특별시 노원구 노원로 49 (공릉동),S-OIL,Y,1497,성동구,37.625918,127.085533
2,강서오곡셀프주유소,서울특별시 강서구 벌말로 254 (오곡동),SK에너지,Y,1497,성동구,37.555284,126.768567
3,수유동주유소,서울특별시 강북구 도봉로 395 (수유동),GS칼텍스,Y,1498,성동구,37.642140,127.029568
4,풀페이주유소,서울특별시 구로구 경인로 41 (온수동),SK에너지,N,1499,성동구,37.489965,126.825487
5,도림주유소,서울 영등포구 도림로 343 (도림동),알뜰주유소,Y,1499,영등포구,37.507656,126.900191
6,(주)대청에너지 대청주유소,서울 영등포구 가마산로 328 (대림동),GS칼텍스,N,1499,영등포구,37.498556,126.895791
7,(주)강서오일,서울 영등포구 도신로 151 (도림동),현대오일뱅크,N,1499,영등포구,37.506964,126.901468
8,서경주유소,서울 동작구 대림로 46 (신대방동),현대오일뱅크,N,1499,동작구,37.487947,126.908240
9,신일셀프주유소,서울 중랑구 상봉로 58 (망우동),SK에너지,Y,1499,중랑구,37.590907,127.093834

In [189]:
import folium
map = folium.Map(location = [price_bottom_10_frm['lat'][0] , price_bottom_10_frm['lng'][0]])
map
folium.CircleMarker(location = [price_bottom_10_frm['lat'][0] , price_bottom_10_frm['lng'][0]]
                   , fill_color = 'blue').add_to(map)
map

In [191]:
for idx in price_top_10_frm.index : 
    folium.CircleMarker([price_top_10_frm['lat'][idx] , price_top_10_frm['lng'][idx]] , 
                        fill_color = 'red' , 
                        fill = True).add_to(map)
map